"""agent_runs

Revision ID: ff10984da6d5
Revises: d89900b862e3
Create Date: 2026-08-19 10:22:23.641069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff10984da6d5'
down_revision: Union[str, None] = 'd89900b862e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('ONBOARDING', 'RESEARCH', 'CREATIVE', 'GENERATION', 'REVIEWER', name='agent_type'), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_runs')
    # drop_table doesn't drop the enum type it implicitly created — without
    # this, re-running upgrade() after a downgrade fails with DuplicateObject
    # (same gotcha as 001_core_schema.py's user_role).
    sa.Enum(name='agent_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
