"""onboarding_responses

Revision ID: bd17076fb2ab
Revises: 4a1d94f6e8b9
Create Date: 2026-08-19 11:56:57.294624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd17076fb2ab'
down_revision: Union[str, None] = '4a1d94f6e8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('voice', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('product_catalog', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_responses')
    # ### end Alembic commands ###
