"""calendar_events

Revision ID: 98a4a53bcc0a
Revises: bd17076fb2ab
Create Date: 2026-08-23 21:13:03.341214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98a4a53bcc0a'
down_revision: Union[str, None] = 'bd17076fb2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_platforms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('desired_format', sa.String(), nullable=False),
    sa.Column('target_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PIPELINE_RUNNING', 'READY_FOR_REVIEW', 'APPROVED', 'PUBLISHED', 'FAILED', name='calendar_event_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_calendar_events')
    # ### end Alembic commands ###
    # drop_table() alone leaves the enum type behind, breaking re-upgrade.
    sa.Enum(name='calendar_event_status').drop(op.get_bind(), checkfirst=True)
