"""brand_report_pdf

Revision ID: fa23800d332d
Revises: b080bafe185d
Create Date: 2026-08-24 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fa23800d332d'
down_revision: Union[str, None] = 'b080bafe185d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('report_pdf_url', sa.String(), nullable=True))
    op.add_column(
        'brands',
        sa.Column('report_pdf_generated_at', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'report_pdf_generated_at')
    op.drop_column('brands', 'report_pdf_url')
    # ### end Alembic commands ###
