"""brand_settings

Revision ID: f3f97cb5fdf2
Revises: 5b29b584c4fa
Create Date: 2026-09-05 22:55:20.827759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f3f97cb5fdf2'
down_revision: Union[str, None] = '5b29b584c4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Pruned by hand: autogenerate also picked up unrelated drift (langgraph
    # checkpoint tables created by raw SQL at runtime, plus a handful of
    # index-name mismatches on unrelated tables) that has nothing to do with
    # this change — only the new brand_settings table belongs here.
    op.create_table('brand_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('auto_approve_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_threshold', sa.Integer(), nullable=False),
    sa.Column('show_agent_reasoning', sa.Boolean(), nullable=False),
    sa.Column('email_review_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_shift_posting_times', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_settings')
    # ### end Alembic commands ###
