"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import {
  ApiError,
  completeOnboarding,
  fetchNextOnboardingQuestions,
  fetchOnboardingAssets,
  runOnboardingAgent,
  streamOnboardingResearch,
  updateBrand,
  uploadBrandLogo,
  uploadOnboardingAsset,
  type DynamicAnswerSubmit,
  type DynamicQuestion,
  type ExtractedBrandKit,
  type OnboardingAsset,
  type ResearchStreamEvent,
} from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { useBrand } from "@/lib/brand-context";
import { useToast } from "@/components/ui/Toast";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { BrandIdentityCapstone } from "./brand-identity-capstone";
import { SocialConnectionsPanel } from "@/app/social-accounts/social-connections-panel";
import { DynamicQuestionCard } from "./dynamic-question-card";
import { InterviewShell } from "./interview-shell";
import type { AaravMood } from "./aarav-companion";

const PRESET_COLORS = ["#1B4DFF", "#0A1633", "#0E7A4E", "#B46A00", "#6B32C9", "#C9295A"];

// Mirrors apps/api/models/onboarding_dynamic_answer.py::MAX_DYNAMIC_PAGES —
// shown to the user as "page N of up to this many", not enforced here (the
// backend is the real cap; generate_next_page's done=True can end things
// far sooner).
const MAX_DYNAMIC_PAGES = 10;

const UPLOAD_SLOTS: { slot: string; label: string }[] = [
  { slot: "product_photos", label: "Product photos" },
  { slot: "team_photos", label: "Team photos" },
  { slot: "past_social_posts", label: "Past social posts" },
  { slot: "style_guide", label: "Style guide" },
];

function capitalize(value: string): string {
  return value.length > 0 ? value[0].toUpperCase() + value.slice(1) : value;
}

export default function OnboardingInterviewPage() {
  const { token } = useAuth();
  const { selectedBrand, selectedBrandId, refresh: refreshBrands } = useBrand();
  const { push: pushToast } = useToast();
  const router = useRouter();
  // Drives the "we're in AI mode now" entrance below — skipped/simplified
  // entirely when the user has asked for less motion.
  const prefersReducedMotion = useReducedMotion();

  // "questions" is now just the one fixed website/colors step — the old
  // "essentials" page (voice/goals/audience/product/competitors) was
  // removed and folded into Aarav's own dynamic question phase instead,
  // so the fixed portion of the interview is as short as it can be before
  // Aarav starts asking things himself, tailored to this brand.
  const [stage, setStage] = useState<"questions" | "dynamic" | "assets" | "capstone" | "connect">("questions");
  const [isLoaded, setIsLoaded] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // Editable brand-identity capstone (Issue #158) — shown once, after the
  // dynamic-questions phase finishes and Aarav's research+synthesis chain
  // (run-agent) has produced a brand_report, right before "connect
  // socials". isFinishingInterview covers the run-agent call itself (a
  // real LLM chain — can take tens of seconds); isSavingCapstone covers
  // persisting the user's edits.
  const [brandReportDraft, setBrandReportDraft] = useState<Record<string, unknown> | null>(null);
  const [isFinishingInterview, setIsFinishingInterview] = useState(false);
  const [isSavingCapstone, setIsSavingCapstone] = useState(false);

  // Adaptive, LLM-generated follow-up questions (Issue #153) — run after
  // the fixed website/colors step above. dynamicPageIndex is the page
  // CURRENTLY on screen (0 until the first page loads); each page's
  // questions are generated by Aarav from every answer given so far,
  // including every earlier dynamic page.
  const [dynamicPageIndex, setDynamicPageIndex] = useState(0);
  const [dynamicQuestions, setDynamicQuestions] = useState<DynamicQuestion[]>([]);
  const [dynamicAnswers, setDynamicAnswers] = useState<Record<string, string | string[]>>({});
  const [isDynamicLoading, setIsDynamicLoading] = useState(false);
  // Purely cosmetic: a free-tier LLM call generating several thoughtful,
  // specific multiple-choice questions can genuinely take a while — this
  // swaps the loading copy after a few seconds so a slow-but-working
  // response doesn't read as "stuck" during the wait.
  const [isDynamicLoadingSlow, setIsDynamicLoadingSlow] = useState(false);
  // Drives the companion's "listening" mood while a dynamic question's mic
  // is actively recording (see dynamic-question-card.tsx's onVoiceActivity)
  // — real integration between the mascot and what Aarav is doing, not
  // just decorative idle motion.
  const [isVoiceActive, setIsVoiceActive] = useState(false);

  const [colors, setColors] = useState<string[]>([]);
  const [isUploadingLogo, setIsUploadingLogo] = useState(false);

  const [scrapeLog, setScrapeLog] = useState<{ text: string; tone: "log" | "signal" | "done" }[]>([]);
  const [isScraping, setIsScraping] = useState(false);
  const [scrapeDone, setScrapeDone] = useState(false);
  const scrapeAbortRef = useRef<AbortController | null>(null);

  // Real website scrape (Issue #152) — the log above stays a plain search
  // preview; this is the actual "we fetched your site and found a logo,
  // colors, and a summary" suggestion, offered as one-click-accept rather
  // than applied automatically (a brand may prefer its own manual picks).
  const [extractedKit, setExtractedKit] = useState<ExtractedBrandKit | null>(null);
  const [isApplyingKit, setIsApplyingKit] = useState(false);
  const [appliedKit, setAppliedKit] = useState(false);

  // Real asset uploads (Issue #144) — replaces the old decorative "+"
  // slots with actual file pickers backed by OnboardingAsset rows.
  const [assets, setAssets] = useState<OnboardingAsset[]>([]);
  const [uploadingSlot, setUploadingSlot] = useState<string | null>(null);

  // Resume in-progress onboarding — prefill whatever's already been saved
  // (brand colors, uploaded assets) rather than starting from scratch.
  // Deliberately does NOT set isLoaded when token/selectedBrandId are
  // still missing: both AuthProvider and BrandProvider resolve those
  // asynchronously (a localStorage read and a fetch, respectively), so on
  // first mount this effect can run once with both still null before
  // either is ready. If that early, empty pass flipped isLoaded to true,
  // the scrape-autostart effect below (gated on isLoaded) would fire
  // immediately with no token/brand, bail out inside runScrape, and then
  // never get a second chance — its own dependencies wouldn't change again
  // once isLoaded was already true. Waiting for real values here is what
  // lets that effect's dependency array pick up the transition from "not
  // ready" to "ready".
  useEffect(() => {
    let cancelled = false;
    async function load() {
      if (!token || !selectedBrandId) return;
      try {
        const existingAssets = await fetchOnboardingAssets(token, selectedBrandId).catch(() => []);
        if (cancelled) return;
        setAssets(existingAssets);
        if (selectedBrand?.colors) setColors(selectedBrand.colors);
      } finally {
        if (!cancelled) setIsLoaded(true);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
    // Only re-run when the brand actually changes, not on every selectedBrand object refresh.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token, selectedBrandId]);

  useEffect(() => () => scrapeAbortRef.current?.abort(), []);

  const runScrape = useCallback(() => {
    if (!token || !selectedBrandId) return;
    scrapeAbortRef.current?.abort();
    const controller = new AbortController();
    scrapeAbortRef.current = controller;

    setScrapeLog([]);
    setScrapeDone(false);
    setIsScraping(true);
    setExtractedKit(null);
    setAppliedKit(false);

    function handleEvent(event: ResearchStreamEvent) {
      if (event.event === "log" && typeof event.data.text === "string") {
        setScrapeLog((current) => [...current, { text: event.data.text as string, tone: "log" }]);
      } else if (event.event === "signal" && typeof event.data.title === "string") {
        setScrapeLog((current) => [
          ...current,
          { text: `Found: ${event.data.title as string}`, tone: "signal" },
        ]);
      } else if (event.event === "extracted") {
        const extractedColors = Array.isArray(event.data.colors) ? (event.data.colors as string[]) : [];
        const socialLinks =
          event.data.social_links && typeof event.data.social_links === "object"
            ? (event.data.social_links as Record<string, string>)
            : {};
        setExtractedKit({
          logoUrl: typeof event.data.logo_url === "string" ? event.data.logo_url : null,
          colors: extractedColors,
          summary: typeof event.data.summary === "string" ? event.data.summary : null,
          socialLinks,
        });
        // Pre-select what Aarav found as a starting point — still just a
        // suggestion until Continue actually saves it, and every swatch
        // (extracted or preset) stays individually toggleable below so
        // the user can add/remove any of them before moving on.
        if (extractedColors.length > 0) {
          setColors((current) => Array.from(new Set([...current, ...extractedColors])));
        }
      } else if (event.event === "done") {
        setScrapeLog((current) => [
          ...current,
          { text: `Done — ${event.data.count ?? 0} signal(s) captured.`, tone: "done" },
        ]);
        setScrapeDone(true);
      }
    }

    streamOnboardingResearch(token, selectedBrandId, handleEvent, controller.signal)
      .catch((err) => {
        if (controller.signal.aborted) return;
        setScrapeLog((current) => [
          ...current,
          {
            text: err instanceof ApiError ? err.message : "Research preview failed.",
            tone: "done",
          },
        ]);
      })
      .finally(() => {
        if (!controller.signal.aborted) setIsScraping(false);
      });
  }, [token, selectedBrandId]);

  // Kick off the scrape automatically the first time this step shows.
  useEffect(() => {
    if (isLoaded && token && selectedBrandId && stage === "questions" && scrapeLog.length === 0) {
      runScrape();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoaded, token, selectedBrandId, stage]);

  const memoryItems = useMemo(
    () => [
      { label: "Website research", done: scrapeDone },
      { label: "Brand colors & logo", done: colors.length > 0 },
      { label: "Brand assets (optional)", done: assets.length > 0, optional: true },
    ],
    [scrapeDone, colors, assets]
  );

  async function handleLogoChange(file: File | null) {
    if (!file || !token || !selectedBrandId) return;
    setIsUploadingLogo(true);
    try {
      const brand = await uploadBrandLogo(token, selectedBrandId, file);
      await refreshBrands();
      if (brand.colors) setColors(brand.colors);
      pushToast("Logo uploaded.", "success");
    } catch (err) {
      pushToast(err instanceof ApiError ? err.message : "Failed to upload logo", "error");
    } finally {
      setIsUploadingLogo(false);
    }
  }

  function toggleColor(hex: string) {
    setColors((current) => (current.includes(hex) ? current.filter((c) => c !== hex) : [...current, hex]));
  }

  // Applies the real website-scrape's logo (Issue #152) as the brand's
  // own — one click, but never automatic. Colors extracted from the same
  // scrape are handled separately: they're pre-selected into the shared,
  // individually-toggleable swatch grid below (see the "extracted" event
  // handler above) rather than needing their own apply step, so a brand
  // can freely mix extracted and manually-picked colors before Continue
  // saves whichever ones ended up selected.
  async function useExtractedLogo() {
    if (!extractedKit?.logoUrl || !token || !selectedBrandId) return;
    setIsApplyingKit(true);
    try {
      await updateBrand(token, selectedBrandId, { logo_url: extractedKit.logoUrl });
      await refreshBrands();
      setAppliedKit(true);
      pushToast("Applied the logo from your website.", "success");
    } catch (err) {
      pushToast(err instanceof ApiError ? err.message : "Failed to apply the extracted logo", "error");
    } finally {
      setIsApplyingKit(false);
    }
  }

  async function handleAssetUpload(slot: string, file: File | null) {
    if (!file || !token || !selectedBrandId) return;
    setUploadingSlot(slot);
    try {
      const asset = await uploadOnboardingAsset(token, selectedBrandId, slot, file);
      setAssets((current) => [...current.filter((a) => a.slot !== slot), asset]);
      pushToast("Uploaded.", "success");
    } catch (err) {
      pushToast(err instanceof ApiError ? err.message : "Failed to upload file", "error");
    } finally {
      setUploadingSlot(null);
    }
  }

  // Colors (extracted + manually toggled, all one selectable pool — see
  // the swatch grid below) save here on Continue; the logo has its own
  // immediate "Use this logo" apply button instead, since there's only
  // one to accept/reject rather than a set to toggle.
  async function saveColors(): Promise<void> {
    if (!token || !selectedBrandId || colors.length === 0) return;
    setIsSaving(true);
    try {
      await updateBrand(token, selectedBrandId, { colors });
    } catch (err) {
      pushToast(err instanceof ApiError ? err.message : "Failed to save your answer", "error");
    } finally {
      setIsSaving(false);
    }
  }

  function goToConnect() {
    setStage("connect");
  }

  // Runs after the dynamic-questions phase reports done: marks onboarding
  // complete, then runs Aarav's research+synthesis chain (run-agent) so
  // there's a brand_report to show on the editable capstone screen. Never
  // strands the user — any failure here (completeOnboarding or run-agent)
  // falls straight through to "connect" exactly like the old behavior,
  // since a missing/stale brand_report can still be filled in later from
  // Brand Data.
  async function finishInterview() {
    if (!token || !selectedBrandId) {
      goToConnect();
      return;
    }
    try {
      await completeOnboarding(token, selectedBrandId);
    } catch {
      // Best-effort — onboarding can still be completed later from
      // /onboarding if the user skipped everything here. Not a blocker
      // for reaching the finishing step.
    }

    setIsFinishingInterview(true);
    try {
      const brand = await runOnboardingAgent(token, selectedBrandId);
      if (brand.brand_report && Object.keys(brand.brand_report).length > 0) {
        setBrandReportDraft(brand.brand_report);
        setStage("capstone");
        return;
      }
    } catch {
      // Research/synthesis is a real LLM chain that can fail (unconfigured
      // provider, transient error) — degrade to skipping the capstone
      // rather than blocking the user from finishing onboarding at all.
    } finally {
      setIsFinishingInterview(false);
    }
    goToConnect();
  }

  async function saveCapstoneAndConnect(edited: Record<string, unknown>) {
    if (!token || !selectedBrandId) {
      goToConnect();
      return;
    }
    setIsSavingCapstone(true);
    try {
      await updateBrand(token, selectedBrandId, { brand_report: edited });
      await refreshBrands();
    } catch (err) {
      pushToast(err instanceof ApiError ? err.message : "Failed to save your edits", "error");
    } finally {
      setIsSavingCapstone(false);
    }
    goToConnect();
  }

  // Loads AI-generated page `pageIndex`, first submitting `answers` (the
  // page just finished — empty on the very first call). Degrades to
  // finishing onboarding outright if the dynamic phase itself can't load,
  // same "never strand the user" spirit as finishInterview/goToConnect
  // above.
  const loadDynamicPage = useCallback(
    async (pageIndex: number, answers: DynamicAnswerSubmit[]) => {
      if (!token || !selectedBrandId) return;
      setIsDynamicLoading(true);
      try {
        const result = await fetchNextOnboardingQuestions(token, selectedBrandId, pageIndex, answers);
        if (result.done || result.questions.length === 0) {
          // Aarav's dynamic phase is the last *question-asking* step — the
          // asset library after this is a totally optional add-anything
          // step, not another question, so it gets its own stage rather
          // than counting toward "how many things does Aarav ask."
          setStage("assets");
          return;
        }
        setDynamicQuestions(result.questions);
        setDynamicAnswers({});
        setDynamicPageIndex(result.page_index);
      } catch (err) {
        pushToast(
          err instanceof ApiError ? err.message : "Couldn't load Aarav's next questions — finishing up instead.",
          "error"
        );
        goToConnect();
      } finally {
        setIsDynamicLoading(false);
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [token, selectedBrandId]
  );

  function enterDynamicPhase() {
    setStage("dynamic");
    loadDynamicPage(0, []);
  }

  useEffect(() => {
    if (!isDynamicLoading) {
      setIsDynamicLoadingSlow(false);
      return;
    }
    const timer = setTimeout(() => setIsDynamicLoadingSlow(true), 6000);
    return () => clearTimeout(timer);
  }, [isDynamicLoading]);

  function setDynamicAnswer(questionId: string, value: string | string[]) {
    setDynamicAnswers((current) => ({ ...current, [questionId]: value }));
  }

  function handleDynamicContinue() {
    const answers: DynamicAnswerSubmit[] = dynamicQuestions.map((question) => ({
      question,
      answer: dynamicAnswers[question.id] ?? (question.type === "chips" ? [] : ""),
    }));
    loadDynamicPage(dynamicPageIndex, answers);
  }

  function handleDynamicSkip() {
    // Skipping this page submits nothing for it (the backend only
    // persists answers it's actually given) but still advances — Aarav
    // just won't have this page's signal for the next one.
    loadDynamicPage(dynamicPageIndex, []);
  }

  async function handleContinue() {
    await saveColors();
    enterDynamicPhase();
  }

  function handleSkip() {
    enterDynamicPhase();
  }

  if (!selectedBrand) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-canvas p-8">
        <EmptyState
          title="No brand yet"
          description="Finish creating your brand first."
          action={<Button onClick={() => router.push("/signup/brand")}>Go to brand setup</Button>}
        />
      </div>
    );
  }

  if (stage === "dynamic") {
    // The one moment the interview visibly shifts from a fixed form to
    // Aarav actually thinking — page 1 gets a distinct perspective/scale
    // entrance (skipped under prefers-reduced-motion); later pages just
    // fade, so the "we're in AI mode now" signal doesn't repeat and wear
    // out.
    const isFirstDynamicPage = dynamicPageIndex <= 1;
    const isLoadingScreen = isDynamicLoading || dynamicQuestions.length === 0;
    const mood: AaravMood = isVoiceActive ? "listening" : isLoadingScreen ? "thinking" : "idle";
    const caption = isVoiceActive
      ? undefined
      : isFinishingInterview
        ? "Putting together your brand identity…"
        : isLoadingScreen && isDynamicLoadingSlow
          ? "A few well-chosen options beat a quick guess…"
          : isLoadingScreen
            ? undefined
            : `Page ${dynamicPageIndex || 1} of up to ${MAX_DYNAMIC_PAGES} — tailored to what you've told me.`;

    return (
      <InterviewShell mood={mood} caption={caption} stepLabel="STEP 2 OF 4 · ASKING SOMETHING NEW">
        <div style={{ perspective: 1200 }}>
          <AnimatePresence mode="wait">
            {isLoadingScreen ? (
              <motion.div
                key="dynamic-loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center gap-3 rounded-[18px] border border-line-soft bg-white p-10 text-center shadow-modal"
              >
                <div className="h-8 w-8 animate-spin rounded-full border-2 border-brand-200 border-t-brand-600" />
                <p className="text-sm text-ink-400">
                  {isFinishingInterview
                    ? "Aarav is putting together your brand identity…"
                    : "Aarav is thinking of what to ask next…"}
                </p>
                {isDynamicLoadingSlow && !isFinishingInterview && (
                  <p className="text-xs text-ink-300">
                    Still working on it — a few well-chosen options beat a quick guess.
                  </p>
                )}
              </motion.div>
            ) : (
              <motion.div
                key={`dynamic-page-${dynamicPageIndex}`}
                initial={
                  prefersReducedMotion
                    ? { opacity: 0 }
                    : isFirstDynamicPage
                      ? { opacity: 0, rotateX: -22, scale: 0.9, y: 28 }
                      : { opacity: 0, y: 14 }
                }
                animate={{ opacity: 1, rotateX: 0, scale: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{
                  duration: prefersReducedMotion ? 0.15 : isFirstDynamicPage ? 0.7 : 0.35,
                  ease: [0.16, 1, 0.3, 1],
                }}
                className="space-y-4 rounded-[18px] border border-line-soft bg-white p-6 shadow-modal"
              >
                {dynamicQuestions.map((question) => (
                  <DynamicQuestionCard
                    key={question.id}
                    question={question}
                    value={dynamicAnswers[question.id] ?? (question.type === "chips" ? [] : "")}
                    onChange={(value) => setDynamicAnswer(question.id, value)}
                    token={token}
                    brandId={selectedBrandId}
                    onVoiceActivity={setIsVoiceActive}
                  />
                ))}

                <div className="flex items-center justify-between border-t border-line-faint pt-[18px]">
                  <Button
                    variant="outline"
                    onClick={finishInterview}
                    disabled={isDynamicLoading || isFinishingInterview}
                    isLoading={isFinishingInterview}
                  >
                    Skip to social connections
                  </Button>
                  <div className="flex items-center gap-3">
                    <button
                      type="button"
                      onClick={handleDynamicSkip}
                      disabled={isDynamicLoading}
                      className="text-[13.5px] font-semibold text-ink-300"
                    >
                      Skip this page
                    </button>
                    <Button onClick={handleDynamicContinue} isLoading={isDynamicLoading}>
                      Continue
                    </Button>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </InterviewShell>
    );
  }

  if (stage === "assets") {
    // A totally optional add-anything step after Aarav's own questions are
    // done — deliberately not the fixed page nor part of the dynamic
    // phase, since it isn't really a *question* at all.
    return (
      <InterviewShell
        mood={isFinishingInterview ? "thinking" : "happy"}
        caption={isFinishingInterview ? "Putting together your brand identity…" : "Almost done — anything else to add?"}
        stepLabel="ALMOST DONE"
      >
        <div>
          <h1 className="mb-1.5 text-[32px] font-bold leading-[1.12] tracking-tight text-ink-950">
            Drop in anything that shows your brand at its best
          </h1>
          <p className="mb-6 text-sm text-ink-400">
            Product photos, past posts, a style guide — totally optional, and you can always add more later.
          </p>

          <div className="rounded-[18px] border border-line-soft bg-white p-6 shadow-modal">
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              {UPLOAD_SLOTS.map(({ slot, label }) => {
                const uploaded = assets.find((a) => a.slot === slot);
                const isUploading = uploadingSlot === slot;
                const isImage = uploaded?.content_type.startsWith("image/");
                return (
                  <label
                    key={slot}
                    className={
                      "flex aspect-square cursor-pointer flex-col items-center justify-center gap-1.5 overflow-hidden rounded-[13px] border-[1.5px] p-2.5 text-center " +
                      (uploaded ? "border-solid border-brand-200 bg-brand-50" : "border-dashed border-ink-100 bg-canvas")
                    }
                  >
                    {isUploading ? (
                      <span className="text-[11.5px] font-semibold text-ink-500">Uploading…</span>
                    ) : uploaded ? (
                      isImage ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img src={uploaded.url} alt={uploaded.filename} className="h-full w-full object-cover" />
                      ) : (
                        <>
                          <span className="text-lg">✓</span>
                          <span className="line-clamp-2 text-[11px] font-semibold leading-tight text-ink-600">
                            {uploaded.filename}
                          </span>
                        </>
                      )
                    ) : (
                      <>
                        <span className="text-lg text-ink-100">＋</span>
                        <span className="text-[11.5px] font-semibold leading-tight text-ink-500">{label}</span>
                      </>
                    )}
                    <input
                      type="file"
                      className="hidden"
                      disabled={isUploading}
                      aria-label={`Upload ${label}`}
                      onChange={(e) => handleAssetUpload(slot, e.target.files?.[0] ?? null)}
                    />
                  </label>
                );
              })}
            </div>

            <div className="mt-6 flex items-center justify-end gap-3 border-t border-line-faint pt-[18px]">
              <button
                type="button"
                onClick={finishInterview}
                disabled={isFinishingInterview}
                className="text-[13.5px] font-semibold text-ink-300"
              >
                Skip
              </button>
              <Button onClick={finishInterview} isLoading={isFinishingInterview}>
                Continue
              </Button>
            </div>
          </div>
        </div>
      </InterviewShell>
    );
  }

  if (stage === "capstone" && brandReportDraft) {
    return (
      <InterviewShell mood="happy" caption="Here's what I learned." stepLabel="STEP 3 OF 4 · BRAND IDENTITY">
        <div>
          <h1 className="mb-1.5 text-[32px] font-bold leading-[1.12] tracking-tight text-ink-950">
            Here&apos;s what Aarav learned
          </h1>
          <p className="mb-6 text-sm text-ink-400">
            This is your brand&apos;s identity doc — every other agent reads it. Edit anything before
            continuing; you can always come back to it later from Brand Data.
          </p>

          <BrandIdentityCapstone
            report={brandReportDraft}
            isSaving={isSavingCapstone}
            onContinue={saveCapstoneAndConnect}
          />
        </div>
      </InterviewShell>
    );
  }

  if (stage === "connect") {
    return (
      <InterviewShell mood="happy" caption="All set — let's get you connected." stepLabel="STEP 4 OF 4 · DISTRIBUTION">
        <div className="max-w-[720px]">
          <h1 className="mb-1.5 text-[32px] font-bold leading-[1.12] tracking-tight text-ink-950">
            Connect where you publish
          </h1>
          <p className="mb-6 text-sm text-ink-400">
            Connect one to finish. You can add, remove or re-authorize any of these later in Settings.
          </p>

          <SocialConnectionsPanel />

          <div className="mt-5 flex items-center gap-3 rounded-2xl border border-line-soft bg-white p-4">
            <div className="h-[34px] w-[34px] shrink-0 rounded-full bg-gradient-to-br from-brand-600 to-brand-200" />
            <p className="flex-1 text-[13px] leading-relaxed text-ink-700">
              Aarav has what he needs to start building your brand memory. You can keep answering
              questions any time from Onboarding in Settings.
            </p>
            <Button onClick={() => router.push("/")}>Enter Raindeer</Button>
          </div>
        </div>
      </InterviewShell>
    );
  }

  // stage === "questions" — the one fixed step: confirm the website Aarav
  // scraped, and pick a palette/logo. Everything after this is Aarav's own
  // adaptive phase (see the "dynamic" stage above).
  const socialLinkEntries = Object.entries(extractedKit?.socialLinks ?? {});
  const lastLogLine = scrapeLog.length > 0 ? scrapeLog[scrapeLog.length - 1].text : null;
  const questionsMood: AaravMood = isScraping ? "reading" : scrapeDone ? "happy" : "idle";
  const questionsCaption = isScraping ? lastLogLine : scrapeDone ? "Found some good signal — take a look." : undefined;

  return (
    <InterviewShell mood={questionsMood} caption={questionsCaption} stepLabel="STEP 1 OF 4 · WEBSITE & BRAND KIT">
      <div>
        <div className="mb-4 flex items-center justify-between gap-3">
          <p className="text-xs text-ink-300">
            Reading{" "}
            <b className="text-ink-600">
              {(selectedBrand.product_catalog?.website as string | undefined) ?? "your public presence"}
            </b>{" "}
            for real, live signals.
          </p>
          <button
            type="button"
            onClick={finishInterview}
            disabled={isFinishingInterview}
            className="shrink-0 text-[12.5px] font-semibold text-ink-300 hover:text-brand-600"
          >
            Skip to social connections
          </button>
        </div>

        <div className="rounded-[18px] border border-line-soft bg-white p-6 shadow-modal">
          <h2 className="mb-2 text-2xl font-bold leading-tight tracking-tight text-ink-950">
            Let&apos;s confirm your website &amp; brand colors
          </h2>
          <p className="mb-5 text-sm leading-relaxed text-ink-400">
            Aarav reads your public site for real, live signals, and offers what it finds — pick your own
            palette and logo below if you&apos;d rather.
          </p>

          <div className="mb-4 flex gap-2.5">
            <div className="flex h-[46px] flex-1 items-center rounded-[11px] border border-line bg-white px-3.5 text-sm text-ink-600">
              {(selectedBrand.product_catalog?.website as string | undefined) ?? "No website on file"}
            </div>
            <Button variant="secondary" onClick={runScrape} isLoading={isScraping}>
              Re-scan
            </Button>
          </div>
          <div
            role="log"
            aria-live="polite"
            className="max-h-[186px] overflow-auto rounded-[13px] border border-line-soft bg-ink-950 p-4 font-mono text-[11.5px] leading-loose text-[#9FB4E8]"
          >
            {scrapeLog.length === 0 ? (
              <div className="text-ink-300">Waiting to start…</div>
            ) : (
              scrapeLog.map((line, index) => (
                <div key={index}>
                  <span
                    className={
                      line.tone === "signal"
                        ? "text-[#6BE3B0]"
                        : line.tone === "done"
                          ? "text-white"
                          : "text-[#7AA2FF]"
                    }
                  >
                    {line.tone === "done" ? "[done]" : line.tone === "signal" ? "[found]" : "[log]"}
                  </span>{" "}
                  {line.text}
                </div>
              ))
            )}
          </div>

          {extractedKit && (extractedKit.logoUrl || extractedKit.colors.length > 0 || socialLinkEntries.length > 0) ? (
            <div className="mt-4 rounded-[13px] border border-brand-100 bg-brand-50 p-4">
              <div className="flex items-center gap-3">
                {extractedKit.logoUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={extractedKit.logoUrl}
                    alt="Logo found on your website"
                    className="h-10 w-10 shrink-0 rounded-lg border border-black/5 object-contain bg-white"
                  />
                ) : null}
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-semibold text-ink-950">
                    {extractedKit.colors.length > 0
                      ? `Found a logo and ${extractedKit.colors.length} color${extractedKit.colors.length === 1 ? "" : "s"} on your site`
                      : "Found a logo on your site"}
                  </p>
                  {extractedKit.summary ? (
                    <p className="mt-0.5 line-clamp-2 text-[11.5px] text-ink-400">{extractedKit.summary}</p>
                  ) : null}
                  {extractedKit.colors.length > 0 ? (
                    <p className="mt-1 text-[11.5px] text-ink-400">
                      Pre-selected below — tap any swatch to add or remove it.
                    </p>
                  ) : null}
                  {socialLinkEntries.length > 0 ? (
                    <p className="mt-1.5 text-[11.5px] text-ink-400">
                      Also linked from the site:{" "}
                      {socialLinkEntries.map(([platform, url], index) => (
                        <span key={platform}>
                          <a
                            href={url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="font-semibold text-brand-600 underline underline-offset-2"
                          >
                            {capitalize(platform)}
                          </a>
                          {index < socialLinkEntries.length - 1 ? ", " : ""}
                        </span>
                      ))}
                    </p>
                  ) : null}
                </div>
                {extractedKit.logoUrl ? (
                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    onClick={useExtractedLogo}
                    isLoading={isApplyingKit}
                    disabled={appliedKit}
                  >
                    {appliedKit ? "Logo applied" : "Use this logo"}
                  </Button>
                ) : null}
              </div>
            </div>
          ) : null}

          <h4 className="mb-2 mt-6 text-xs font-bold uppercase tracking-wide text-ink-400">
            Pick your palette — tap any color to toggle it
          </h4>
          <div className="mb-4 flex flex-wrap gap-3">
            {Array.from(new Set([...extractedKit?.colors ?? [], ...PRESET_COLORS])).map((hex) => {
              const isFound = extractedKit?.colors.includes(hex) ?? false;
              const isSelected = colors.includes(hex);
              return (
                <motion.button
                  key={hex}
                  type="button"
                  aria-pressed={isSelected}
                  aria-label={`Toggle color ${hex}`}
                  onClick={() => toggleColor(hex)}
                  whileTap={{ scale: 0.93 }}
                  animate={{ scale: isSelected ? 1.04 : 1 }}
                  transition={{ type: "spring", stiffness: 500, damping: 25 }}
                  className={
                    "relative flex flex-col items-center gap-1.5 rounded-2xl border-2 p-1 " +
                    (isSelected ? "border-brand-600" : "border-transparent hover:border-line")
                  }
                >
                  {isFound && (
                    <span className="absolute -right-1 -top-1 rounded-full bg-brand-600 px-1.5 py-[1px] text-[9px] font-bold text-white shadow-sm">
                      found
                    </span>
                  )}
                  <span
                    className="relative flex h-[62px] w-[62px] items-center justify-center rounded-[10px] border border-black/5"
                    style={{ backgroundColor: hex }}
                  >
                    {isSelected && (
                      <motion.span
                        initial={{ scale: 0, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        transition={{ type: "spring", stiffness: 600, damping: 20 }}
                        className="flex h-6 w-6 items-center justify-center rounded-full bg-white/90 text-xs font-bold text-brand-700 shadow-sm"
                      >
                        ✓
                      </motion.span>
                    )}
                  </span>
                  <span className="font-mono text-[11px] text-ink-500">{hex}</span>
                </motion.button>
              );
            })}
          </div>
          <div className="grid grid-cols-2 gap-3">
            <label className="flex cursor-pointer flex-col items-center justify-center gap-1 rounded-[13px] border-[1.5px] border-dashed border-ink-100 bg-canvas p-4 text-center">
              <span className="text-sm font-bold text-ink-950">
                {isUploadingLogo ? "Uploading…" : "Drop your logo"}
              </span>
              <span className="text-[11.5px] text-ink-300">SVG or PNG</span>
              <input
                type="file"
                accept="image/*"
                aria-label="Upload logo"
                className="hidden"
                disabled={isUploadingLogo}
                onChange={(e) => handleLogoChange(e.target.files?.[0] ?? null)}
              />
            </label>
            <div className="rounded-[13px] border border-line-soft p-3.5">
              <div className="mb-2 text-[11.5px] font-bold text-ink-600">
                {selectedBrand.logo_url ? "Your logo" : "No logo uploaded yet"}
              </div>
              {selectedBrand.logo_url ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={selectedBrand.logo_url}
                  alt={`${selectedBrand.name} logo`}
                  className="h-9 w-9 rounded-lg object-cover"
                />
              ) : (
                <div className="flex gap-1.5">
                  {colors.map((c) => (
                    <i key={c} className="block h-[22px] w-[22px] rounded-md" style={{ background: c }} />
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="mt-6 flex items-center justify-between border-t border-line-faint pt-[18px]">
            <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11.5px] text-ink-300">
              {memoryItems
                .filter((item) => !item.optional)
                .map((item) => (
                  <span key={item.label} className={item.done ? "font-semibold text-brand-600" : ""}>
                    {item.done ? "✓ " : "○ "}
                    {item.label}
                  </span>
                ))}
            </div>
            <div className="flex items-center gap-3">
              <button type="button" onClick={handleSkip} className="text-[13.5px] font-semibold text-ink-300">
                Skip
              </button>
              <Button onClick={handleContinue} isLoading={isSaving}>
                Continue
              </Button>
            </div>
          </div>
        </div>

        <p className="mt-[18px] text-center text-[11.5px] text-ink-200">
          Answers are stored in your brand database and reused by Ved, Keshav, Kavi and Neer.
        </p>
      </div>
    </InterviewShell>
  );
}
