from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from apps.api.auth.router import router as auth_router
from apps.api.config import get_settings
from apps.api.middleware.error_handlers import register_error_handlers
from apps.api.middleware.logging import RequestLoggingMiddleware, configure_json_logging
from apps.api.middleware.rate_limit import RateLimitMiddleware
from apps.api.observability import init_sentry
from apps.api.routers.analytics import router as analytics_router
from apps.api.routers.arena import router as arena_router
from apps.api.routers.brands import router as brands_router
from apps.api.routers.calendar import router as calendar_router
from apps.api.routers.onboarding import router as onboarding_router
from apps.api.routers.review import router as review_router
from apps.api.routers.social_accounts import router as social_accounts_router

settings = get_settings()
configure_json_logging()
init_sentry(settings.sentry_dsn, settings.environment)

app = FastAPI(title="Raindeer Social API")
register_error_handlers(app)
app.add_middleware(RateLimitMiddleware)
app.add_middleware(RequestLoggingMiddleware)
# Added last so it wraps every other middleware (Starlette makes the most
# recently added middleware the outermost layer). That's required, not just
# tidy: it ensures CORS headers are still attached to responses generated by
# RateLimitMiddleware/RequestLoggingMiddleware (e.g. a 429) — if CORS sat
# inside those layers, a rate-limited response would skip it and the browser
# would report a CORS failure instead of surfacing the real error.
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.include_router(auth_router)
app.include_router(analytics_router)
app.include_router(arena_router)
app.include_router(brands_router)
app.include_router(calendar_router)
app.include_router(onboarding_router)
app.include_router(review_router)
app.include_router(social_accounts_router)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "environment": settings.environment}
